name: Backend Regression Tests

on:
  push:
    branches: [ "test" ] # Roda quando você envia código para essas branches
  pull_request:
    branches: [ "test" ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18 # Ou a versão que você usa no seu PC

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Cucumber Tests
      run: npm test
      env:
        # Aqui você mapeia o Secret do GitHub para a variável que o seu código espera
        BASE_URL: ${{ secrets.BASE_URL }}
        URL_AUTH_MICROSOFT: ${{ secrets.URL_AUTH_MICROSOFT }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        SCOPE: ${{ secrets.SCOPE }}
        # Adicione todas as outras que estiverem no seu .env

    - name: Upload Report
      if: always() # Garante que o relatório seja salvo mesmo se o teste falhar
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-report
        path: reports/ # Ajuste para a pasta onde seu relatório é gerado